### ISSUE TITLE
多数据仓 多域名push 怎么配置问题

### ISSUE THREAD

**Issue by ccworld1000** [huiwang/hexo-baidu-url-submit#25]
如果一份数据存在多个数据仓
每个数据仓对应一个域名
那对应多个host 怎么配置

**Comment by yansheng836** [comment]
多数据数据仓库可参考(`hexo\_config.yml`)：
```yml
deploy:
- type: git
  repository: 
     github: 
     coding: 
  branch: master
  # 发布时，同时进行百度推送
- type: baidu_url_submitter
```
