### ISSUE TITLE
hexo g 的时候

### ISSUE THREAD

**Issue by yangtengfei** [huiwang/hexo-baidu-url-submit#28]
FATAL duplicated mapping key at line 83, column 3:
      type: baidu_url_submitter
      ^

**Comment by yansheng836** [comment]
？不看提示的吗？type重复了，如果有多个可以用`-type`的形式，就像：
```yml
deploy:
- type: git
  repository: 
     github: https://github.com/……
  branch: master
  # 发布时，同时进行百度推送
- type: baidu_url_submitter
```
